/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.QuanlychisodienController;
import Model.CustomException;
import Model.HoaDon;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author anhbu
 */
public class JFromThemthangtieptheo extends javax.swing.JFrame {
    QuanlychisodienController qlcsdC = new QuanlychisodienController();
    
    
    /**
     * Creates new form JFromThemthangtieptheo
     */
    public JFromThemthangtieptheo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMakh_tttt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtChisomoi_tttt = new javax.swing.JTextField();
        btnThem_TTTT = new javax.swing.JButton();
        btnThoat_TTTT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Thêm tháng tiếp theo");

        jLabel3.setText("Mã khách hàng");

        jLabel5.setText("Chỉ số mới");

        btnThem_TTTT.setText("Thêm");
        btnThem_TTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_TTTTActionPerformed(evt);
            }
        });

        btnThoat_TTTT.setText("Thoát");
        btnThoat_TTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat_TTTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem_TTTT)
                                .addGap(43, 43, 43)
                                .addComponent(btnThoat_TTTT))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMakh_tttt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtChisomoi_tttt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMakh_tttt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtChisomoi_tttt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_TTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat_TTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThem_TTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_TTTTActionPerformed
        // TODO add your handling code here:
        try{
            //Để chèn tự động tháng tiếp theo thì mình phải lấy ra tháng hiện tại, chỉ số hiện tại
            if(txtMakh_tttt.getText().isEmpty() || txtChisomoi_tttt.getText().isEmpty())
                throw new CustomException("Bạn cần nhập đủ thông tin mã tháng, Chỉ số điện mới");
            ArrayList<HoaDon> listHoaDon_kh = new ArrayList<>();
            listHoaDon_kh = qlcsdC.findByMakhForthemThangTiepTheo(txtMakh_tttt.getText());
            if(listHoaDon_kh.isEmpty()){
                throw new CustomException("Mã khách hàng bạn nhập không tồn tại");
            }
            
            HoaDon hd = new HoaDon();
            hd.setMaHD(listHoaDon_kh.get(listHoaDon_kh.size()-1).getMaHD());
            hd.setNguoiDung(listHoaDon_kh.get(listHoaDon_kh.size()-1).getNguoiDung());
            hd.setThang(listHoaDon_kh.get(listHoaDon_kh.size()-1).getThang());
            hd.setSoDienDau(listHoaDon_kh.get(listHoaDon_kh.size()-1).getSoDienDau());
            hd.setSoDienCuoi(listHoaDon_kh.get(listHoaDon_kh.size()-1).getSoDienCuoi());
            if(Integer.parseInt(txtChisomoi_tttt.getText()) < hd.getSoDienCuoi())
                throw new CustomException("Lỗi số điện mới phải lớn hơn hoặc bằng số điện của tháng trước");
            //get all hd
            ArrayList<HoaDon> listHoaDon = new ArrayList<>();
            listHoaDon = qlcsdC.getList_Chisodien();
            //get component to insert insert in new hoadon
            String mahd;
            if(listHoaDon.size() < 10){
                mahd = "hd0"+(listHoaDon.size()+1);
            }
            else {
                mahd = "hd"+(listHoaDon.size()+1);
            }
            String makh = txtMakh_tttt.getText();
            String current_mathang = hd.getThang().getMaThang().toString();
            int mathang_new;
            if(current_mathang.indexOf("1")==4 && current_mathang.indexOf("2")==5){
                
                char new_mahd = (char)(Integer.parseInt(String.valueOf(current_mathang.charAt(3)))+1);
                current_mathang.replace(current_mathang.charAt(3), new_mahd);
                current_mathang.replace(current_mathang.charAt(4), '0');
                current_mathang.replace(current_mathang.charAt(5), '1');
                mathang_new = Integer.parseInt(current_mathang);
            }
            else
                mathang_new = Integer.parseInt(hd.getThang().getMaThang()) + 1;
            
            int sodiendau = hd.getSoDienCuoi();
            int sodiencuoi = Integer.parseInt(txtChisomoi_tttt.getText());
            
            //insert thang moi vao CSDl
            qlcsdC.themHoadon(mahd, makh, mathang_new, sodiendau, sodiencuoi);
            JOptionPane.showMessageDialog(null, "Thêm thành công!");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        catch(CustomException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnThem_TTTTActionPerformed

    private void btnThoat_TTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat_TTTTActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát", "Confirm", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnThoat_TTTTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFromThemthangtieptheo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFromThemthangtieptheo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFromThemthangtieptheo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFromThemthangtieptheo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFromThemthangtieptheo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem_TTTT;
    private javax.swing.JButton btnThoat_TTTT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtChisomoi_tttt;
    private javax.swing.JTextField txtMakh_tttt;
    // End of variables declaration//GEN-END:variables
}
